api/urls.py
from django.urls import path, include


urlpatterns = [
    path("accounts/", include("api.accounts.urls")),
    path("posts/", include("api.posts.urls")),
]

notifications/urls.py
from django.urls import path
from . import views


app_name = "notifs"
urlpatterns = [
    path("notifs-list/", views.NotificationsListView.as_view(), name="notifs_list"),
    path(
        "notif-detail/<int:pk>/",
        views.NotificationDetailView.as_view(),
        name="notif_detail",
    ),
    path(
        "delete-notif/<int:pk>/",
        views.DeleteNotificationView.as_view(),
        name="delete_notif",
    ),
    path("mark-read/<int:pk>/", views.MarkNotifReadView.as_view(), name="mark_read"),
    path(
        "mark-all-notifs-read/", views.MarkAllReadView.as_view(), name="mark_all_read"
    ),
    path("delete-all-read/", views.DeleteAllRead.as_view(), name="delete_all_read"),
]

zwitter/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("pages.urls")),
    path("accounts/", include("accounts.urls")),
    path("posts/", include("posts.urls")),
    path("notifications/", include("notifications.urls")),
    path("api/", include("api.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

notifications/models.py
from django.db import models
from accounts.models import User
from django.urls import reverse


class Notification(models.Model):
    user = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="notifications"
    )
    title = models.CharField(max_length=255, default="New Notification")
    message = models.CharField(max_length=255)
    created = models.DateTimeField(auto_now_add=True)
    is_read = models.BooleanField(default=False)
    mute = models.BooleanField(default=False)

    class Meta:
        ordering = ("-created",)

    def __str__(self):
        return f"{self.user} - {self.created}"

    def get_absolute_url(self):
        return reverse("notifs:notif_detail", args=[self.pk])

notifications/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views import View
from .models import Notification
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib import messages
from django.http import HttpResponseForbidden


class NotificationsListView(LoginRequiredMixin, View):
    def get(self, request):
        notifs = Notification.objects.filter(user=request.user)
        return render(request, "notifications/notifs_list.html", {"notifs": notifs})


class NotificationDetailView(LoginRequiredMixin, View):
    def get(self, request, pk):
        notif = get_object_or_404(Notification, pk=pk)
        if notif.user != request.user:
            return HttpResponseForbidden("You're not allowed on this page.")
        notif.is_read = True
        notif.save()
        return render(request, "notifications/notif_detail.html", {"notif": notif})


class DeleteNotificationView(LoginRequiredMixin, View):
    def get(self, request, pk):
        notif = get_object_or_404(Notification, pk=pk)
        if notif.user != request.user:
            return HttpResponseForbidden("You're not allowed on this page.")
        notif.delete()
        messages.success(request, "Notification deleted", "success")
        return redirect("notifs:notifs_list")


class MarkNotifReadView(LoginRequiredMixin, View):
    def get(self, request, pk):
        notif = get_object_or_404(Notification, pk=pk)
        if notif.user != request.user:
            return HttpResponseForbidden("You're not allowed on this page.")
        notif.is_read = True
        notif.save()
        messages.success(request, "Marked as read", "success")
        return redirect("notifs:notifs_list")


class MarkAllReadView(View):
    def get(self, request):
        Notification.objects.filter(user=request.user, is_read=False).update(
            is_read=True
        )
        messages.success(request, "Marked all as read", "success")
        return redirect("notifs:notifs_list")


class DeleteAllRead(View):
    def get(self, request):
        Notification.objects.filter(user=request.user, is_read=True).delete()
        messages.success(request, "Notifications deleted", "success")
        return redirect("notifs:notifs_list")

templates/notifications/notif_detail.html
{% extends 'base.html' %}

{% block body %}

<div class="card mx-auto m-2 col-lg-9 d-flex justify-content-center">
  <div class="card text-light p-3"
    style="background: linear-gradient(180deg, rgba(61,12,115,1) 0%, rgba(52,8,71,1) 100%)">
    <div class="card-body">
      <h5 class="card-title">{% if notif.title %}{{ notif.title }}{% endif %} {% if not notif.is_read %}
        <b>(NEW!)</b>{% endif %}
      </h5>
      <h6 class="card-subtitle mb-2 text-light">{{ notif.created|timesince }} ago</h6>
      <p class="card-text my-3">{{ notif.message|safe }}</p>
      <a href="{% url 'notifs:delete_notif' notif.pk %}" class="btn btn-danger">Delete</a>
    </div>
  </div>
</div>

{% endblock %}

templates/notifications/notifs_list.html
{% extends 'base.html' %}

{% block body %}

<h1>Notifications</h1>
<br>

<a class="btn btn-primary" href="{% url 'notifs:mark_all_read' %}">Mark all as read</a>
<a class="btn btn-danger" href="{% url 'notifs:delete_all_read' %}">Delete all read</a>

{% for notif in notifs %}
<div class="card mx-auto m-2 col-lg-6 d-flex justify-content-center">
  <div class="card text-light p-2 notif">
    <div class="card-body">
      <h5 class="card-title">{{ notif.title }} {% if not notif.is_read %}
        <b>(NEW!)</b>{% endif %}
      </h5>
      <h6 class="card-subtitle mb-2 text-light">{{ notif.created|timesince }} ago</h6>
      <a class="btn btn-info" href="{{ notif.get_absolute_url }}">Open</a>
      {% if not notif.is_read %}
      <a class="btn btn-primary" href="{% url 'notifs:mark_read' notif.pk %}">Mark as read</a>
      {% endif %}
      <a class="btn btn-danger" href="{% url 'notifs:delete_notif' notif.pk %}">Delete</a>
    </div>
  </div>
</div>
{% endfor %}

{% endblock %}