accounts/urls.py
from django.urls import path
from . import views


app_name = "accounts"
urlpatterns = [
    path("register/", views.UserRegisterView.as_view(), name="user_register"),
    path("verify/", views.Verify.as_view(), name="verify"),
    path("login/", views.LoginView.as_view(), name="login"),
    path("logout/", views.LogoutView.as_view(), name="logout"),
    path(
        "password-reset/", views.UserPasswordResetView.as_view(), name="password_reset"
    ),
    path(
        "password-reset/done/",
        views.UserPasswordResetDoneView.as_view(),
        name="password_reset_done",
    ),
    path(
        "password-reset-confirm/<uidb64>/<token>/",
        views.UserPasswordResetConfirmView.as_view(),
        name="password_reset_confirm",
    ),
    path(
        "password-reset-complete/",
        views.UserPasswordResetCompleteView.as_view(),
        name="password_reset_complete",
    ),
    path(
        "profile/<int:pk>/",
        views.ProfileView.as_view(),
        name="profile",
    ),
    path(
        "change-username/",
        views.ChangeUsernameView.as_view(),
        name="change_username",
    ),
    path("follow/<int:pk>/", views.FollowView.as_view(), name="follow"),
    path(
        "follow-requests/",
        views.FollowRequests.as_view(),
        name="follow_requests",
    ),
    path("accept-follow/<int:pk>/", views.AcceptFollow.as_view(), name="accept_follow"),
    path(
        "decline-follow/<int:pk>/", views.DeclineFollow.as_view(), name="decline_follow"
    ),
    path(
        "followers/<int:pk>/",
        views.FollowersView.as_view(),
        name="followers",
    ),
    path(
        "following/<int:pk>/",
        views.FollowingView.as_view(),
        name="following",
    ),
    path("mute/<int:pk>/", views.MuteView.as_view(), name="mute"),
]

api/accounts/urls.py
from django.urls import path
from . import views

from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
    TokenBlacklistView,
)

from django_rest_passwordreset.views import (
    reset_password_confirm,
    reset_password_request_token,
    reset_password_validate_token,
)


app_name = "api_accounts"
urlpatterns = [
    path("register/", views.UserRegisterAPIView.as_view(), name="register"),
    path("verify/", views.VerifyOTPCodeAPIView.as_view(), name="verify"),
    path("token/", TokenObtainPairView.as_view(), name="token_obtain_pair"),
    path("token/refresh/", TokenRefreshView.as_view(), name="token_refresh"),
    path("token/blacklist/", TokenBlacklistView.as_view(), name="token_blacklist"),
    path(
        "password-reset/validate_token/",
        reset_password_validate_token,
        name="reset_password_validate",
    ),
    path(
        "password-reset/confirm/", reset_password_confirm, name="reset_password_confirm"
    ),
    path(
        "password-reset/", reset_password_request_token, name="reset_password_request"
    ),
    path("user/<int:pk>/", views.UserAPIView.as_view(), name="user"),
    path(
        "update-username/",
        views.ChangeUsernameAPIView.as_view(),
        name="update_username",
    ),
    path(
        "is-followed/<int:pk>/", views.IsFollowedAPIView.as_view(), name="is_followed"
    ),
    path("follow/<int:pk>/", views.FollowAPIView.as_view(), name="follow"),
    path("unfollow/<int:pk>/", views.UnfollowAPIView.as_view(), name="unfollow"),
    path(
        "follow-requests/",
        views.FollowRequestsAPIView.as_view(),
        name="follow_requests",
    ),
    path("following/<int:pk>/", views.FollowingAPIView.as_view(), name="following"),
    path("followers/<int:pk>/", views.FollowersAPIView.as_view(), name="followers"),
    path(
        "accept-follow/<int:pk>/",
        views.AcceptFollowRequestAPIView.as_view(),
        name="accept_follow_request",
    ),
    path(
        "decline-follow/<int:pk>/",
        views.DeclineFollowRequestAPIView.as_view(),
        name="decline_follow_request",
    ),
    path("mute/<int:pk>/", views.MuteAPIView.as_view(), name="mute"),
    path("unmute/<int:pk>/", views.UnMuteAPIView.as_view(), name="unmute"),
    path("is-followed", views.IsFollowedAPIView.as_view(), name="is_followed"),
]

api/urls.py
from django.urls import path, include


urlpatterns = [
    path("accounts/", include("api.accounts.urls")),
    path("posts/", include("api.posts.urls")),
]

posts/urls.py
from django.urls import path
from . import views


app_name = "posts"
urlpatterns = [
    path("", views.PostsListView.as_view(), name="posts"),
    path("create-post/", views.CreatePostView.as_view(), name="create_post"),
    path(
        "create-post/attach-picture/",
        views.AttachPictureView.as_view(),
        name="attach_picture",
    ),
    path(
        "create-post/attach-video/",
        views.AttachVideoView.as_view(),
        name="attach_video",
    ),
    path(
        "post-detail/<int:pk>/",
        views.PostDetailView.as_view(),
        name="post_detail",
    ),
    path("tag/<str:title>/", views.TagPostView.as_view(), name="tag"),
    path("like/<int:pk>/", views.LikePostView.as_view(), name="like"),
    path("reply/<int:pk>/", views.ReplyView.as_view(), name="reply"),
    path("repost/<int:pk>/", views.RepostView.as_view(), name="repost"),
    path("delete-post/<int:pk>/", views.DeletePostView.as_view(), name="delete_post"),
]

zwitter/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("pages.urls")),
    path("accounts/", include("accounts.urls")),
    path("posts/", include("posts.urls")),
    path("notifications/", include("notifications.urls")),
    path("api/", include("api.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views import View
from .forms import UserRegisterForm, VerifyForm, LoginForm, ChangeUsernameForm
from .models import User, OTPCode, Following
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.views import (
    PasswordResetView,
    PasswordResetDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView,
)
from django.urls import reverse, reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from posts.models import Post
from django.urls import reverse
from . import tasks
from django.core.paginator import Paginator
from utils import notify, add_view


class UserRegisterView(View):
    form_class = UserRegisterForm
    template_name = "accounts/register.html"

    def get(self, request):
        return render(request, self.template_name, {"form": self.form_class()})

    def post(self, request):
        form = self.form_class(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            tasks.send_otp_code_task.delay(cd["email"])
            request.session["user_registration_info"] = {
                "email": cd["email"],
                "password": cd["password"],
            }
            messages.success(request, "Code sent.", "success")
            return redirect("accounts:verify")
        messages.error(
            request, "Invalid form. Please fix the issues listed below.", "danger"
        )
        return render(request, self.template_name, {"form": form})


class Verify(View):
    form_class = VerifyForm
    template_name = "accounts/verify.html"

    def get(self, request):
        return render(request, self.template_name, {"form": self.form_class()})

    def post(self, request):
        form = self.form_class(request.POST)

        if form.is_valid():
            email = request.session["user_registration_info"]["email"]
            password = request.session["user_registration_info"]["password"]
            otp = get_object_or_404(OTPCode, email=email)

            if otp.code == form.cleaned_data["code"]:
                user = User.objects.create_user(email=email, password=password)
                messages.success(request, "Signed up successfully.", "success")
                del request.session["user_registration_info"]
                otp.delete()
                user = authenticate(request, email=email, password=password)
                login(request, user)
                return redirect("accounts:profile", pk=user.pk)

            messages.error(request, "Wrong code", "danger")
            return render(request, self.template_name, {"form": self.form_class()})

        return render(request, self.template_name, {"form": form})


class LoginView(View):
    form_class = LoginForm
    template_name = "accounts/login.html"

    def setup(self, request, *args, **kwargs):
        self.next = request.GET.get("next", None)
        return super().setup(request, *args, **kwargs)

    def get(self, request):
        return render(request, self.template_name, {"form": self.form_class()})

    def post(self, request):
        form = self.form_class(request.POST)
        if form.is_valid():
            cd = form.cleaned_data

            user = authenticate(request, email=cd["email"], password=cd["password"])
            if user:
                login(request, user)
                messages.success(request, "Logged in successfully.", "success")
                if self.next:
                    return redirect(self.next)
                return redirect("accounts:profile", pk=user.pk)

            messages.error(request, "username and/or password are wrong.", "danger")
        return render(request, self.template_name, {"form": form})


class LogoutView(View):
    def get(self, request):
        if request.user.is_authenticated:
            logout(request)
            messages.success(request, "Logged out successfully", "success")
        else:
            messages.error(request, "You are not logged in.", "danger")
        return redirect("pages:home")


class UserPasswordResetView(PasswordResetView):
    template_name = "accounts/password_reset.html"
    success_url = reverse_lazy("accounts:password_reset_done")
    email_template_name = "accounts/email_template.html"


class UserPasswordResetDoneView(PasswordResetDoneView):
    template_name = "accounts/password_reset_done.html"


class UserPasswordResetConfirmView(PasswordResetConfirmView):
    success_url = reverse_lazy("accounts:password_reset_complete")
    template_name = "accounts/password_reset_confirm.html"


class UserPasswordResetCompleteView(PasswordResetCompleteView):
    template_name = "accounts/password_reset_complete.html"


class ProfileView(View):
    template_name = "accounts/profile.html"

    def get(self, request, pk):
        user = get_object_or_404(User, pk=pk)
        posts = Post.objects.filter(user=user).prefetch_related("tags")
        paginator = Paginator(object_list=posts, per_page=10, orphans=5)
        page_number = request.GET.get("page", 1)
        posts = paginator.get_page(page_number)
        paginator_range = posts.paginator.get_elided_page_range(page_number)
        if request.user == user and not user.username:
            change_username_url = reverse("accounts:change_username")
            messages.warning(
                request,
                f'Your profile is not complete. Add a username <a href="{change_username_url}">here</a>.',
                "warning safe",
            )

        follow_requests = None
        if request.user == user:
            follow_requests = Following.objects.filter(followed=user, accepted=False)

        following = Following.objects.filter(follower=user, accepted=True)
        followers = Following.objects.filter(followed=user, accepted=True)
        is_requested = Following.objects.filter(
            follower=request.user, followed=user, accepted=False
        ).exists()
        is_followed = Following.objects.filter(
            follower=request.user, followed=user, accepted=True
        ).exists()
        is_mute = False
        if is_followed:
            is_mute = Following.objects.get(
                follower=request.user, followed=user, accepted=True
            ).mute

        for post in posts:
            add_view(request, post)

        return render(
            request,
            self.template_name,
            {
                "posts": posts,
                "profile_user": user,
                "follow_requests": follow_requests,
                "following": following,
                "followers": followers,
                "paginator_range": paginator_range,
                "is_requested": is_requested,
                "is_followed": is_followed,
                "is_mute": is_mute,
            },
        )


class ChangeUsernameView(LoginRequiredMixin, View):
    form_class = ChangeUsernameForm
    template_name = "accounts/change_username.html"

    def get(self, request):
        return render(request, self.template_name, {"form": self.form_class()})

    def post(self, request):
        form = self.form_class(request.POST)
        if form.is_valid():
            username = form.cleaned_data["username"]
            if not User.objects.filter(username=username).exists():
                request.user.username = username
                request.user.save()
                messages.success(request, "Username successfully changed.", "success")
                return redirect("accounts:profile", pk=request.user.pk)
            else:
                messages.error(request, "This username already exists.", "danger")
        return render(request, self.template_name, {"form": form})


class FollowView(LoginRequiredMixin, View):
    def setup(self, request, *args, **kwargs):
        self.next = request.GET.get("next")
        return super().setup(request, *args, **kwargs)

    def get(self, request, pk):
        user_to_follow = get_object_or_404(User, pk=pk)

        if user_to_follow == request.user:
            messages.error(request, "You can't follow yourself. (Obviously!)", "danger")
            return redirect("accounts:profile", pk=user_to_follow.pk)

        if Following.objects.filter(
            follower=request.user, followed=user_to_follow
        ).exists():
            Following.objects.get(
                follower=request.user, followed=user_to_follow
            ).delete()
            notify(
                user_to_follow,
                "Unfollowed",
                f'<a href="{request.user.get_absolute_url()}">{request.user}</a> has unfollowed you.',
            )
            messages.success(request, "Unfollowed", "success")
            return redirect("accounts:profile", pk=user_to_follow.pk)

        Following.objects.create(
            follower=request.user, followed=user_to_follow, accepted=False
        )
        notify(
            user_to_follow,
            "New Follow Request",
            f'<a href="{request.user.get_absolute_url()}">{request.user}</a> wants to follow you. Check out your <a href="/accounts/follow-requests/"> follow requests</a>.',
        )
        messages.success(request, "Following request sent", "success")
        return redirect("accounts:profile", pk=user_to_follow.pk)


class FollowRequests(LoginRequiredMixin, View):
    def get(self, request):
        follow_requests = Following.objects.filter(
            followed=request.user, accepted=False
        )
        return render(
            request,
            "accounts/follow_requests.html",
            {"follow_requests": follow_requests},
        )


class AcceptFollow(LoginRequiredMixin, View):
    def get(self, reqeust, pk):
        following = get_object_or_404(Following, pk=pk)
        if reqeust.user == following.followed:
            following.accepted = True
            following.save()
            notify(

templates/accounts/change_username.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block body %}
<form action="" method="post">
  {% csrf_token %}
  {{ form|crispy }}
  <button type="submit" class="btn btn-primary">Submit</button>
</form>
{% endblock %}

templates/accounts/email_template.html
Someone asked for password reset for email {{ email }}. Follow the link below:
{{ protocol}}://{{ domain }}{% url 'accounts:password_reset_confirm' uidb64=uid token=token %}

templates/accounts/follow_requests.html
{% extends 'base.html' %}

{% block body %}
<h1>Follow Reqeusts</h1>
{% for follow_request in follow_requests %}
<h3 class="text-center">{{ follow_request.follower }}</h3>
<div class="d-flex justify-content-center">
  <a href="{% url 'accounts:accept_follow' follow_request.pk %}" class="m-1 btn btn-primary">Accept</a>
  <a href="{% url 'accounts:decline_follow' follow_request.pk %}" class="m-1 btn btn-danger">Decline</a>
</div>
{% if not forloop.last %}
<hr>
{% endif %}
{% empty %}
<h3>You currently don't have any follow requests.</h3>
{% endfor %}
{% endblock %}

templates/accounts/follows.html
{% extends 'base.html' %}

{% block body %}

{% if followers %}
<h1>{{ profile_user }}'s Followers</h1>
{% else %}
<h1>{{ profile_user }}'s Following</h1>
{% endif %}

{% for follow in follows %}

{% if followers %}
<h3 class="text-center"><a href="{{ follow.follower.get_absolute_url }}">{{ follow.follower }}</a></h3>
{% else %}
<a href="{{ follow.followed.get_absolute_url }}">
  <h3>{{ follow.followed }}</h3>
</a>
{% if profile_user == user %}
<a href="{% url 'accounts:follow' follow.followed.pk %}?next={{ request.get_full_path }}"
  class="m-1 btn btn-danger">Unfollow</a>
{% endif %}
{% endif %}

{% if not forloop.last %}
<hr>
{% endif %}

{% empty %}
<h2 class="text-center">Wow, Such empty :(</h2>
{% endfor %}

{% endblock %}

templates/accounts/login.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block body %}
<form action="" method="post">
    {% csrf_token %}
    {{ form|crispy }}
    <button class="btn btn-primary">Login</button>
</form>
<p>Forgot your password? <a href="{% url 'accounts:password_reset' %}">Reset Password</a></p>
<p>Don't have an account? <a href="{% url 'accounts:user_register' %}">Join Now</a></p>
{% endblock %}

templates/accounts/password_reset.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block body %}
<h1>Password Reset</h1>
<form action="" method="post">
    {% csrf_token %}
    {{ form|crispy }}
    <button class="btn btn-primary">Send</button>
</form>
{% endblock %}

templates/accounts/password_reset_complete.html
{% extends 'base.html' %}

{% block body %}
<h2>Password Reset Completed.</h2>
<a href="{% url 'accounts:login' %}">Login</a>
{% endblock %}

templates/accounts/password_reset_confirm.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block body %}
{% if validlink %}
<h2>Password Reset Confirm</h2>
<form action="" method="post">
    {% csrf_token %}
    {{ form|crispy }}
    <button class="btn btn-primary">Change</button>
</form>
{% else %}
<h2>This link is not valid.</h2>
{% endif %}
{% endblock %}

templates/accounts/password_reset_done.html
{% extends 'base.html' %}

{% block body %}
<p class="alert alert-primary" role="alert">Email Sent</p>
{% endblock %}

templates/accounts/profile.html
{% extends 'base.html' %}

{% block body %}

<h1>{{ profile_user }}</h1>

<h4>
  <a class="text-reset text-decoration-none" href="{% url 'accounts:followers' profile_user.pk %}"><u>Followers</u>
    <span class="text-secondary"> {{ followers.count }}</span></a>
</h4>
<h4>
  <a class="text-reset text-decoration-none" href="{% url 'accounts:following' profile_user.pk %}"><u>Following</u>
    <span class="text-secondary">{{ following.count }}</span></a>
</h4>

<br>

{% if profile_user == user %}
<a class="btn btn-primary detail-button" href="{% url 'posts:create_post' %}">Add Post</a>
<a class="btn btn-primary detail-button" href="{% url 'accounts:password_reset'%}">Change Password</a>
<a class="btn btn-primary detail-button" href="{% url 'accounts:change_username'%}">Change Username</a>
{% if follow_requests %}
<br><br>
<p>You have new follow requests. <a href="{% url 'accounts:follow_requests' %}">Check them out!</a></p>
{% endif %}
{% elif user.is_authenticated %}

{% if is_followed %}
<a class="btn btn-primary detail-button btn-lg" href="{% url 'accounts:follow' profile_user.pk %}">Unfollow</a>
<a class="btn btn-primary detail-button btn-lg" href="{% url 'accounts:mute' profile_user.pk %}">
  {% if is_mute %} Unmute {% else %} Mute {% endif %}</a>
{% elif is_requested %}
<a class="btn btn-primary detail-button btn-lg" href="{% url 'accounts:follow' profile_user.pk %}">Cancel follow
  request</a>
{% else %}
<a class="btn btn-primary detail-button btn-lg" href="{% url 'accounts:follow' profile_user.pk %}">Follow</a>
{% endif %}

{% endif %}
<hr>
<h2>{% if profile_user == user %} Your {% else %} {{ profile_user|title }}'s {% endif %} Posts</h2>
{% include 'inc/posts.html' %}

{% endblock %}

templates/accounts/register.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block body %}
<form action="" method="post">
    {% csrf_token %}
    {{ form|crispy }}
    <button class="btn btn-primary">Submit</button>
</form>
{% endblock %}

templates/accounts/verify.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block body %}
<form action="" method="post">
    {% csrf_token %}
    {{ form|crispy }}
    <button class="btn btn-primary">Verify</button>
</form>
{% endblock %}