accounts/urls.py
from django.urls import path
from . import views


app_name = "accounts"
urlpatterns = [
    path("register/", views.UserRegisterView.as_view(), name="user_register"),
    path("verify/", views.Verify.as_view(), name="verify"),
    path("login/", views.LoginView.as_view(), name="login"),
    path("logout/", views.LogoutView.as_view(), name="logout"),
    path(
        "password-reset/", views.UserPasswordResetView.as_view(), name="password_reset"
    ),
    path(
        "password-reset/done/",
        views.UserPasswordResetDoneView.as_view(),
        name="password_reset_done",
    ),
    path(
        "password-reset-confirm/<uidb64>/<token>/",
        views.UserPasswordResetConfirmView.as_view(),
        name="password_reset_confirm",
    ),
    path(
        "password-reset-complete/",
        views.UserPasswordResetCompleteView.as_view(),
        name="password_reset_complete",
    ),
    path(
        "profile/<int:pk>/",
        views.ProfileView.as_view(),
        name="profile",
    ),
    path(
        "change-username/",
        views.ChangeUsernameView.as_view(),
        name="change_username",
    ),
    path("follow/<int:pk>/", views.FollowView.as_view(), name="follow"),
    path(
        "follow-requests/",
        views.FollowRequests.as_view(),
        name="follow_requests",
    ),
    path("accept-follow/<int:pk>/", views.AcceptFollow.as_view(), name="accept_follow"),
    path(
        "decline-follow/<int:pk>/", views.DeclineFollow.as_view(), name="decline_follow"
    ),
    path(
        "followers/<int:pk>/",
        views.FollowersView.as_view(),
        name="followers",
    ),
    path(
        "following/<int:pk>/",
        views.FollowingView.as_view(),
        name="following",
    ),
    path("mute/<int:pk>/", views.MuteView.as_view(), name="mute"),
]

api/posts/urls.py
from django.urls import path
from . import views


app_name = "api_posts"
urlpatterns = [
    path("", views.PostsListAPIView.as_view(), name="posts_list"),
    path("<int:pk>/", views.PostAPIView.as_view(), name="post_detail"),
    path("user/<int:pk>/", views.UserPostsListAPIView.as_view(), name="user_posts"),
    path("tag/<str:title>/", views.TagPostsAPIView.as_view(), name="tag_posts"),
    path("create/", views.PostCreateAPIView.as_view(), name="create"),
    path("repost/<int:pk>/", views.RepostAPIView.as_view(), name="repost"),
    path("reply/<int:pk>/", views.ReplyAPIView.as_view(), name="reply"),
    path("like/<int:pk>/", views.LikePostAPIView.as_view(), name="like"),
    path("delete/<int:pk>/", views.DeletePostAPIView.as_view(), name="delete"),
    path("update/<int:pk>/", views.UpdatePostAPIView.as_view(), name="updaet"),
    path("is-liked/<int:pk>/", views.IsLikedAPIView.as_view(), name="is_liked"),
]

api/urls.py
from django.urls import path, include


urlpatterns = [
    path("accounts/", include("api.accounts.urls")),
    path("posts/", include("api.posts.urls")),
]

notifications/urls.py
from django.urls import path
from . import views


app_name = "notifs"
urlpatterns = [
    path("notifs-list/", views.NotificationsListView.as_view(), name="notifs_list"),
    path(
        "notif-detail/<int:pk>/",
        views.NotificationDetailView.as_view(),
        name="notif_detail",
    ),
    path(
        "delete-notif/<int:pk>/",
        views.DeleteNotificationView.as_view(),
        name="delete_notif",
    ),
    path("mark-read/<int:pk>/", views.MarkNotifReadView.as_view(), name="mark_read"),
    path(
        "mark-all-notifs-read/", views.MarkAllReadView.as_view(), name="mark_all_read"
    ),
    path("delete-all-read/", views.DeleteAllRead.as_view(), name="delete_all_read"),
]

pages/urls.py
from django.urls import path
from . import views


app_name = "pages"
urlpatterns = [
    path("", views.HomeView.as_view(), name="home"),
]

posts/urls.py
from django.urls import path
from . import views


app_name = "posts"
urlpatterns = [
    path("", views.PostsListView.as_view(), name="posts"),
    path("create-post/", views.CreatePostView.as_view(), name="create_post"),
    path(
        "create-post/attach-picture/",
        views.AttachPictureView.as_view(),
        name="attach_picture",
    ),
    path(
        "create-post/attach-video/",
        views.AttachVideoView.as_view(),
        name="attach_video",
    ),
    path(
        "post-detail/<int:pk>/",
        views.PostDetailView.as_view(),
        name="post_detail",
    ),
    path("tag/<str:title>/", views.TagPostView.as_view(), name="tag"),
    path("like/<int:pk>/", views.LikePostView.as_view(), name="like"),
    path("reply/<int:pk>/", views.ReplyView.as_view(), name="reply"),
    path("repost/<int:pk>/", views.RepostView.as_view(), name="repost"),
    path("delete-post/<int:pk>/", views.DeletePostView.as_view(), name="delete_post"),
]

zwitter/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("pages.urls")),
    path("accounts/", include("accounts.urls")),
    path("posts/", include("posts.urls")),
    path("notifications/", include("notifications.urls")),
    path("api/", include("api.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/models.py
from django.db import models
from accounts.models import User
from django.core.validators import FileExtensionValidator
from django.core.exceptions import ValidationError
from django.urls import reverse
from .managers import ProductManager


class Tag(models.Model):
    title = models.CharField(max_length=255, unique=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("posts:tag", args=[self.title])


class Post(models.Model):
    TEXT = "TXT"
    IMAGE = "IMG"
    VIDEO = "VID"
    REPOST = "REP"
    POST_TYPE_CHOICES = [
        (TEXT, "Text"),
        (IMAGE, "Image"),
        (VIDEO, "Video"),
        (REPOST, "Repost"),
    ]

    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="posts")
    body = models.TextField(max_length=4000, null=True, blank=True)
    image = models.ImageField(null=True, blank=True)
    video = models.FileField(
        validators=[
            FileExtensionValidator(
                allowed_extensions=["MOV", "avi", "mp4", "webm", "mkv"]
            )
        ],
        null=True,
        blank=True,
    )
    post_type = models.CharField(max_length=3, choices=POST_TYPE_CHOICES, default=TEXT)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    tags = models.ManyToManyField(Tag, related_name="posts", blank=True)
    root = models.ForeignKey(
        "self", on_delete=models.CASCADE, related_name="replies", blank=True, null=True
    )
    reposted_from = models.ForeignKey(
        "self", on_delete=models.CASCADE, related_name="reposts", null=True, blank=True
    )

    objects = ProductManager()

    class Meta:
        ordering = ("-updated",)

    def __str__(self):
        return f"{self.pk} - {self.user} - {self.post_type}"

    def save(self, *args, **kwargs):
        if not (self.image and self.video):
            if self.image:
                self.post_type = self.IMAGE
            elif self.video:
                self.post_type = self.VIDEO
            elif self.reposted_from:
                self.post_type = self.REPOST
            else:
                self.post_type = self.TEXT
            return super().save(*args, **kwargs)
        else:
            raise ValidationError("A post can't have 2 media files at the same time.")

    def get_absolute_url(self):
        return reverse("posts:post_detail", args=[self.pk])

    def is_liked(self, user):
        if not user.is_authenticated:
            return False
        return Like.objects.filter(post=self, user=user).exists()

    @property
    def views_count(self):
        return PostView.objects.filter(post=self).count()


class Like(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="likes")
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name="likes")

    def __str__(self):
        return f"{self.user} liked [{self.post}]"


class PostView(models.Model):
    ip = models.GenericIPAddressField()
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name="views")

    def __str__(self):
        return f"{self.ip} - {self.post}"

posts/forms.py
from django import forms
from .models import Post
from django.core.exceptions import ValidationError
from django.core.validators import FileExtensionValidator


class CreatePostForm(forms.Form):
    body = forms.CharField(max_length=4000, widget=forms.Textarea, required=True)
    tags = forms.CharField(
        max_length=255,
        required=False,
        widget=forms.TextInput(attrs={"placeholder": "separate with commas"}),
    )


class AttachPictureForm(forms.Form):
    image = forms.ImageField()


class AttachVideoForm(forms.Form):
    video = forms.FileField(
        validators=[FileExtensionValidator(["MOV", "avi", "mp4", "webm", "mkv"])]
    )


class PostAdminForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = (
            "user",
            "body",
            "post_type",
            "image",
            "video",
            "tags",
            "root",
            "reposted_from",
        )

    def clean(self):
        cd = self.cleaned_data
        if not (cd["image"] and cd["video"]):
            return cd
        raise ValidationError("A post can't have 2 media files at the same time.")


class SearchForm(forms.Form):
    q = forms.CharField(max_length=4000, required=False, label="")

api/posts/views.py
from rest_framework.views import APIView
from rest_framework import generics
from rest_framework.response import Response
from posts.models import Post, Tag, Like
from .serializers import PostSerializer, PostCreateUpdateSerializer
from accounts.models import User, Following
from django.shortcuts import get_object_or_404
from rest_framework.permissions import IsAuthenticated
from utils import get_tags_list
from rest_framework import status
from rest_framework.exceptions import ValidationError
from django.db.models import Q


class PostAPIView(APIView):
    def get(self, request, pk):
        post = get_object_or_404(Post, pk=pk)
        serializer = PostSerializer(post, context={"request": request})
        return Response(serializer.data)


class PostsListAPIView(generics.GenericAPIView):
    def get(self, request):
        if request.user.is_authenticated:
            user_followings = Following.objects.filter(
                follower=request.user, accepted=True
            )

            following_users = []
            for following in user_followings:
                following_users.append(following.followed.pk)

            following_users_posts = Post.objects.filter(user__in=following_users)

            normal_posts = Post.objects.filter(~Q(user__in=following_users))

            posts = following_users_posts | normal_posts
        else:
            posts = Post.objects.all()

        q = request.GET.get("q")
        if q:
            posts = posts.search(q)

        page = self.paginate_queryset(posts)

        serializer = PostSerializer(page, many=True, context={"request": request})
        return self.get_paginated_response(serializer.data)


class UserPostsListAPIView(generics.GenericAPIView):
    def get(self, request, pk):
        user = get_object_or_404(User, pk=pk)
        posts = Post.objects.filter(user=user)
        page = self.paginate_queryset(posts)
        serializer = PostSerializer(page, many=True, context={"request": request})
        return self.get_paginated_response(serializer.data)


class TagPostsAPIView(generics.GenericAPIView):
    def get(self, request, title):
        tag = get_object_or_404(Tag, title=title)
        posts = tag.posts.all()
        page = self.paginate_queryset(posts)
        serializer = PostSerializer(page, many=True, context={"request": request})
        return self.get_paginated_response(serializer.data)


class PostCreateAPIView(APIView):
    permission_classes = (IsAuthenticated,)

    def post(self, request):
        serializer = PostCreateUpdateSerializer(
            data=request.data, context={"request": request}
        )
        if serializer.is_valid():
            post = serializer.save()

            return Response(
                {"message": f"{post.post_type} post created."}, status.HTTP_201_CREATED
            )

        return Response({"errors": serializer.errors}, status.HTTP_400_BAD_REQUEST)


class RepostAPIView(APIView):
    permission_classes = (IsAuthenticated,)

    def post(self, request, pk):
        source_post = get_object_or_404(Post, pk=pk)
        post = Post.objects.create(user=request.user, post_type="REP")
        post.reposted_from = (
            source_post.reposted_from if source_post.post_type == "REP" else source_post
        )
        post.tags.set(source_post.tags.all())
        post.save()
        return Response({"message": "Reposted successfully."}, status.HTTP_200_OK)


class ReplyAPIView(APIView):
    permission_classes = (IsAuthenticated,)

    def post(self, request, pk):
        serializer = PostCreateUpdateSerializer(data=request.data)
        if serializer.is_valid():
            root = get_object_or_404(Post, pk=pk)
            data = serializer.validated_data
            if data.get("image") and data.get("video"):
                raise ValidationError("A post can only have one media file.")
            post = Post.objects.create(
                user=request.user,
                body=data["body"],
                image=data.get("image"),
                video=data.get("video"),
            )
            post.tags.set(get_tags_list(data.get("tags", "")))
            post.tags.add(*list(root.tags.all()))
            post.root = root
            post.save()
            return Response(
                {"message": f"{post.post_type} post created."}, status.HTTP_200_OK
            )
        return Response({"errors": serializer.errors}, status.HTTP_400_BAD_REQUEST)


class LikePostAPIView(APIView):
    permission_classes = (IsAuthenticated,)

    def post(self, request, pk):
        post = get_object_or_404(Post, pk=pk)
        like, created = Like.objects.get_or_create(user=request.user, post=post)

        if not created:
            like.delete()
            return Response({"message": "Post unliked."}, status.HTTP_200_OK)

        return Response({"message": "Post liked."}, status.HTTP_200_OK)


class DeletePostAPIView(APIView):
    permission_classes = (IsAuthenticated,)

    def delete(self, request, pk):
        post = get_object_or_404(Post, pk=pk)

        if post.user == request.user:
            post.delete()
            return Response({"message": "Post deleted."}, status.HTTP_200_OK)

        return Response(
            {"message": "This post is not yours to delete."},
            status.HTTP_400_BAD_REQUEST,
        )


class UpdatePostAPIView(APIView):
    permission_classes = (IsAuthenticated,)

    def put(self, request, pk):
        post = get_object_or_404(Post, pk=pk, user=request.user)
        serializer = PostCreateUpdateSerializer(
            instance=post, data=request.data, partial=True
        )

        if serializer.is_valid():
            serializer.save()
            return Response({"message": "Post updated"}, status.HTTP_200_OK)

        return Response({"errors": serializer.errors}, status.HTTP_400_BAD_REQUEST)


class IsLikedAPIView(APIView):
    permission_classes = (IsAuthenticated,)

    def get(self, request, pk):
        post = get_object_or_404(Post, pk=pk)
        is_liked = Like.objects.filter(user=request.user, post=post).exists()
        return Response({"is_liked": is_liked})

templates/inc/messages.html
{% if messages %}
{% for message in messages %}
{% if 'safe' in message.tags %}
<p class="alert alert-{{ message.tags }}" role="alert">{{ message|safe }}</p>
{% else %}
<p class="alert alert-{{ message.tags }}" role="alert">{{ message }}</p>
{% endif %}
{% endfor %}
{% endif %}

templates/inc/navbar.html
{% load static %}
{% load new_notifs_count %}

<nav class="px-5 py-3 navbar navbar-expand-lg navbar-dark text-dark"
  style="background: radial-gradient(circle, rgba(107,21,145,1) 0%, rgba(61,12,115,1) 100%)">
  <div class="container-fluid">

    <img class="navbar-brand" src="{% static 'img/logo.png' %}" height="50px">
    <a class="navbar-brand" href="{% url 'pages:home' %}">Zwitter</a>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'pages:home' %}">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'posts:posts' %}">Posts</a>
        </li>
        {% if not user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'accounts:user_register' %}">Register</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'accounts:login' %}">Login</a>
        </li>
        {% else %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'accounts:profile' user.pk %}">Profile</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'posts:create_post' %}">Add Post</a>
        </li>
        <li class="nav-item pull-right">
          <a class="nav-link" href="{% url 'notifs:notifs_list' %}">
            {% if user|new_notifs_count > 0 %} <b>Notifications ({{ user|new_notifs_count }})</b>
            {% else %}
            Notifications
            {% endif %}</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'accounts:logout' %}">Logout</a>
        </li>
        {% endif %}
    </div>
  </div>
</nav>

templates/inc/posts.html
{% load is_liked %}
{% load like_count %}
{% load reply_count %}

{% for post in posts %}
<div class="card mx-auto m-2 col-lg-6 d-flex justify-content-center">
  <div class="card text-light p-2"
    style="background: linear-gradient(180deg, rgba(61,12,115,1) 0%, rgba(52,8,71,1) 100%)">
    <div class="card-body">
      {% if post.root %}
      <h6>Replied to <a href="{{ post.root.get_absolute_url }}">{{ post.root.user }}</a></h6>
      {% endif %}

      <h5 class="card-title"><a href="{% url 'accounts:profile' post.user.pk %}">{{ post.user }}</a>
        {% if post.post_type == 'REP' %}
        | Reposted from <a href="{{ post.reposted_from.get_absolute_url }}">
          {{ post.reposted_from.user }}</a>
        {% endif %}
      </h5>
      <h6 class="card-subtitle mb-2 text-light">{{ post.updated|timesince }} ago | {{post.views_count}} <svg
          xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-eye"
          viewBox="0 0 16 16">
          <path
            d="M16 8s-3-5.5-8-5.5S0 8 0 8s3 5.5 8 5.5S16 8 16 8zM1.173 8a13.133 13.133 0 0 1 1.66-2.043C4.12 4.668 5.88 3.5 8 3.5c2.12 0 3.879 1.168 5.168 2.457A13.133 13.133 0 0 1 14.828 8c-.058.087-.122.183-.195.288-.335.48-.83 1.12-1.465 1.755C11.879 11.332 10.119 12.5 8 12.5c-2.12 0-3.879-1.168-5.168-2.457A13.134 13.134 0 0 1 1.172 8z" />
          <path d="M8 5.5a2.5 2.5 0 1 0 0 5 2.5 2.5 0 0 0 0-5zM4.5 8a3.5 3.5 0 1 1 7 0 3.5 3.5 0 0 1-7 0z" />
        </svg></h6>
      {% if post.post_type != 'TXT' %}
      {% if post.post_type == 'IMG' %}
      <img class="card-img-top" src="{{ post.image.url }}" alt="Card image cap">
      {% elif post.post_type == 'VID' %}
      <video class="card-img-top" controls>
        <source src="{{ post.video.url }}" type="video/mp4">
      </video>
      {% endif %}
      {% endif %}

      {% if post.post_type == 'REP' %}

      {% if post.reposted_from.post_type != 'TXT' %}
      {% if post.reposted_from.post_type == 'IMG' %}
      <img class="card-img-top" src="{{ post.reposted_from.image.url }}" alt="Card image cap">
      {% elif post.reposted_from.post_type == 'VID' %}
      <video class="card-img-top" controls>
        <source src="{{ post.video.url }}" type="video/mp4">
      </video>
      {% endif %}
      {% else %}
      <p class="card-text my-3">{{ post.reposted_from.body }}</p>
      {% endif %}

      {% else %}
      <p class="card-text my-3">{{ post.body }}</p>
      {% endif %}

      <hr>
      {% if post.tags.all %}
      <p>{% for tag in post.tags.all %} <a href="{{ tag.get_absolute_url }}">#{{ tag }}</a> {% endfor %} </p>
      {% endif %}

      <div class="row d-flex justify-content-center">
        {% if not post|is_liked:user %}
        <a class="btn btn-secondary col-2 m-1" href="{% url 'posts:like' post.pk %}?next={{ request.get_full_path }}">
          <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-heart"
            viewBox="0 0 16 16">
            <path
              d="m8 2.748-.717-.737C5.6.281 2.514.878 1.4 3.053c-.523 1.023-.641 2.5.314 4.385.92 1.815 2.834 3.989 6.286 6.357 3.452-2.368 5.365-4.542 6.286-6.357.955-1.886.838-3.362.314-4.385C13.486.878 10.4.28 8.717 2.01L8 2.748zM8 15C-7.333 4.868 3.279-3.04 7.824 1.143c.06.055.119.112.176.171a3.12 3.12 0 0 1 .176-.17C12.72-3.042 23.333 4.867 8 15z" />
          </svg> {{ post|like_count }}
        </a>
        {% else %}
        <a class="btn btn-danger col-2 m-1" href="{% url 'posts:like' post.pk %}?next={{ request.get_full_path }}">
          <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-heart-fill"
            viewBox="0 0 16 16">
            <path fill-rule="evenodd" d="M8 1.314C12.438-3.248 23.534 4.735 8 15-7.534 4.736 3.562-3.248 8 1.314z" />
          </svg> {{ post|like_count }}
        </a>
        {% endif %}

        <a href="{{ post.get_absolute_url }}" class="btn btn-primary detail-button col-5 m-1">details</a>
        {% if user == post.user %}
        <a class="btn btn-danger col-2 m-1" href="{% url 'posts:delete_post' post.pk %}">Delete</a>
        {% else %}
        <a class="btn btn-secondary col-2 m-1" href="{% url 'posts:repost' post.pk %}">Repost</a>
        {% endif %}
        <a class="btn btn-secondary col-2 m-1" href="{% url 'posts:reply' post.pk %}">Reply {{ post|reply_count }}</a>
      </div>
    </div>
  </div>
</div>
{% empty %}
<h2 class="text-center">Wow, Such empty :(</h2>
{% endfor %}
<br>
{% if posts and posts.paginator.num_pages > 1 %}
<nav aria-label="...">
  <ul class="pagination justify-content-center">
    {% if posts.has_previous %}
    <li class="page-item">
      <a class="page-link" href="{{ request.path }}?page={{ posts.previous_page_number }}">Previous</a>
    </li>
    {% else %}
    <li class="page-item disabled">
      <a class="page-link">Previous</a>
    </li>
    {% endif %}

    {% for page_number in paginator_range %}
    {% if page_number == posts.paginator.ELLIPSIS %}
    <li class="page-item"><a class="page-link">{{ page_number }}</a></li>
    {% else %}
    <li class="page-item {% if page_number == posts.number %}active{% endif %}"><a class="page-link"
        href="{{ request.path }}?page={{ page_number }}">{{ page_number }}</a></li>
    {% endif %}
    {% endfor %}

    {% if posts.has_next %}
    <li class="page-item">
      <a class="page-link" href="{{ request.path }}?page={{ posts.next_page_number }}">Next</a>
    </li>
    {% else %}
    <li class="page-item disabled">
      <a class="page-link">Next</a>
    </li>
    {% endif %}
  </ul>
</nav>
<br><br>
{% endif %}